# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

opt_out_usage

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# Add gradle get version name plugin
# fastlane add_plugin get_version_name

default_platform(:android)

platform :android do 
    versionName = get_version_name(
        gradle_file_path:"app/build.gradle.kts",
        ext_constant_name:"versionName"
    )

    versionCode = get_version_name(
        gradle_file_path:"app/build.gradle.kts",
        ext_constant_name:"versionCode"
    )

    desc "Generate release version"
    lane :release do |options|
        gradle(
            task: "clean"
        )
        gradle(
            task: "assemble",
            build_type: "Release"
        )
    end

    desc "Generate oss version"
    lane :oss do |options|
        gradle(
            task: "clean"
        )
        gradle(
            task: "bundle",
            build_type: "oss"
        )
    end

    desc "Deploy a new version to Google Play"
    lane :deployOSS do
        gradle(
            task: "clean"
        )
        gradle(
            task: "bundle",
            build_type: "oss"
        )
        upload_to_play_store(
            aab: "app/build/outputs/bundle/oss/openZinkBooth-#{versionName}-oss.aab"
        )
    end

    desc "Deploy a new version to GitHub"
    lane :deployGitHubRelease do
        set_github_release(
            repository_name: "oliexdev/openZinkBooth",
            api_token: ENV["OLIEXDEV_GITHUB_API_TOKEN"],
            name: "openZinkBooth #{versionName} release",
            tag_name: "v#{versionName}",
            description: (File.read("metadata/android/en-US/changelogs/#{versionCode}.txt") rescue "No changelog provided"),
            upload_assets: [ "app/build/outputs/apk/release/openZinkBooth-#{versionName}-release.apk" ]
        )
    end
end
